---
title: "Visualizing and Biclustering scRNA-seq data with CAbiNET"
author:
- name: Clemens Kohl
  affiliation: Max Planck Institute for Molecular Genetics, Berlin, Germany
  email: kohl@molgen.mpg.de
- name: Yan Zhao
  affiliation: Max Planck Institute for Molecular Genetics, Berlin, Germany
  email: zhao@molgen.mpg.de
- name: Martin Vingron
  affiliation: Max Planck Institute for Molecular Genetics, Berlin, Germany
  email: vingron@molgen.mpg.de
package: CAbiNet
output:
  BiocStyle::html_document
abstract: |
  CAbiNET allows fast and robust biclustering of single-cell RNA-seq
  through Correspondence Analysis. Clustering results of cells and genes can be
  conviently displayed in a biMAP.
vignette: |
  %\VignetteIndexEntry{Biclustering scRNAseq data with CAbiNET}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  markdown: 
    wrap: sentence
---

```{r, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>", results = "hold")
```

# Vignette is Work in Progress!

# Introduction

# Installation

You can install the devopmental version of the package with:
```{r git_install, eval=FALSE}
devtools::install_github("ClemensKohl/CAbiNet")
```

```{r setup}
library(CAbiNet)
```

# Analyzing data with CAbiNET


# Session info {.unnumbered}

```{r sessionInfo, echo=FALSE}
sessionInfo()
```
