# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComputeSNNasym <- function(SNN, prune) {
    .Call('_CAclust_ComputeSNNasym', PACKAGE = 'CAclust', SNN, prune)
}

rcppeigen_hello_world <- function() {
    .Call('_CAclust_rcppeigen_hello_world', PACKAGE = 'CAclust')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_CAclust_rcppeigen_outerproduct', PACKAGE = 'CAclust', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_CAclust_rcppeigen_innerproduct', PACKAGE = 'CAclust', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_CAclust_rcppeigen_bothproducts', PACKAGE = 'CAclust', x)
}

