# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ComputeSNNasym <- function(SNN, prune, mode) {
    .Call('_CAbiNet_ComputeSNNasym', PACKAGE = 'CAbiNet', SNN, prune, mode)
}

#' WIP replacement for `determine_overlap` function
#' @name calc_overlap
#' @description
#' c++ implementation for calculating the cell-neighour-overlapping among k nearest cell neighbours of each gene.
#' @param cc_adj sparse matrix (dgCMatrix), cell-cell adjacency matrix
#' @param cg_adj sparse matrix (dgCMatrix), cell-gene adjacency matrix
#' @param threshold numeric value between 0 and 1. The cutoff of cell-nqighour-overlapping of each gene.
#' @export
calc_overlap <- function(cc_adj, cg_adj, threshold) {
    .Call('_CAbiNet_calc_overlap', PACKAGE = 'CAbiNet', cc_adj, cg_adj, threshold)
}

#' Deprecated, slower old version of calc_overlap. Only included for testing.
#' @name calc_overlap_deprecated
#' @param cc_adj the cell-cell graph adjacency matrix.
#' @param cg_adj The cell-gene graph adjacency matrix.
#' @export
calc_overlap_deprecated <- function(cc_adj, cg_adj) {
    .Call('_CAbiNet_calc_overlap_deprecated', PACKAGE = 'CAbiNet', cc_adj, cg_adj)
}

